### ISSUE TITLE
dcoker run bug

### ISSUE THREAD

**Issue by lijianl** [bitcoin-sv/docker-sv#3] opened 2022-02-24 09:15 UTC
************************
EXCEPTION: N5boost10filesystem16filesystem_errorE
boost::filesystem::create_directory: File exists: "/home/bitcoin/.bitcoin"
bitcoin in AppInit()

bitcoind: chainparamsbase.cpp:39: const CBaseChainParams& BaseParams(): Assertion `globalChainBaseParams' failed.

**Comment by Danconnolly** [comment] 2022-03-15 22:24
duplicate of https://github.com/bitcoin-sv/docker-sv/issues/5

**Closed by Danconnolly** 2022-03-15 22:24 UTC
