### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by lijianl** [bitcoin-sv/docker-sv#4] opened 2022-02-24 14:53 UTC
EXCEPTION: N5boost10filesystem16filesystem_errorE boost::filesystem::status: Function not implemented: "/home/bitcoin/.bitcoin" bitcoin in AppInit()

**Comment by lijianl** [comment] 2022-03-14 11:17
does any body responsible for the issue

**Comment by Danconnolly** [comment] 2022-03-15 22:24
Duplicate of https://github.com/bitcoin-sv/docker-sv/issues/5

**Closed by Danconnolly** 2022-03-15 22:24 UTC
